### ISSUE TITLE
Extra entries in Hosted zone records

### ISSUE THREAD

**Issue by pzawadzkipz** [williamsandonz/serverless-website-domain#2]
Hi @williamsandonz ,

I went successfully through adding custom domain to our front-end using your serverless plugin and it works well. Thank you for that. 
There was only one issue I had - domain only works with www. I went through Route 53 config and I can see A and AAAA entries created correctly for www, but nothing for without www - which would be the reason why DNS doesn't resolve address without www.

![image](https://user-images.githubusercontent.com/10986039/173811637-a7531295-f505-4f55-9c71-1723d8640067.png)

I am not sure if it's design or not, but in order to make it work without www prefix you need to manually add records in Route 53.
Would it be possible to extend/add functionality to have setting to include those entries? I can try to implement it and if you are ok with it and then add this to npm package. 

I know you can do redirect in Edge Lambda, but I don't think there is always need for using it? Give me your thoughts :)

Thanks!
Pawel

**Comment by williamsandonz** [comment]
Hey @pzawadzkipz . Sorry it's been a long time since I've lookjed at this plugin and I can see something aren't very clear about it how it works  @:(! 

If you look at the updateDnsRecords function you can see it will only create the non WWW variant if both edgeLambda and edgeLambda.redirect and set in the config and if so it will use the value for config.edgeLambda.redirect.from. So basically you can only create both WWW and non WWW if you are using the edgeLambda redirect. I think I decided on this behaviour because assumed you'd always want one to redirect to the other (for Google indexing etc) which perhaps was bad foresight on my part. But if you do use that, it should work fine. If you're still having trouble, paste your config in here and I can take a look.

**Comment by pzawadzkipz** [comment]
Ok! Will have a look at changing the config. Many thanks again :)

**Comment by williamsandonz** [comment]
Closing as not an issue, it's just how plugin works.
